[package]
name = "sevo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-enum-from-into = "0.1.1"
derive_more = "0.99.17"
parse_int = "0.6.0"
strum = "0.24.1"
strum_macros = "0.24.3"
